components:
  - https://gitlab.com/rocketduck/csi-plugin-nfs
description: NFS CSI storage driver
entrypoint: csi-plugin
variables:
  log_level: INFO
  nfs_share:
  node_class: main-worker
  plugin_id: csi.cloudskeleton.eu
  plugin_version: 1.1.0
version: 25.08.09
